### ISSUE TITLE
[Preconception][Report] Line list of women with Outcome- for followup.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#10]
##### Filters - 
Outcome start date
Outcome End date.
Block
PHC
Subcenter

Logic - 
- List of all the women with Outcome encounter. where Outcome = Live birth or Live and Still Birth 
- Questions "Is Child Alive after 28 days" and "Is Mother Alive after 28 days" is not answered.

Purpose - 
To followup the women after 28 days of outcome (Live Birth and Live and stillbirth)

##### Line List -
Block
PHC
Subcenter
Village
Wadi/Vasti
Name
Age
Date of Outcome

Report: [https://reporting.openchs.org/question/568](https://reporting.openchs.org/question/568)

**Comment by garimadosar5** [comment]
QA Notes - 
- This report shows, Number of rows 35. 
    But there are 30 cases of "Live birth" for that question "Is Child Alive after 28 days" is not recorded and there are 6 cases of "Live Birth and Still Birth" for that "Is Child Alive after 28 days" is not recorded.
 - Also, there must be some cases where "Is mother alive after 28 days" is not recorded.

**This is fixed.**

**Comment by ghost** [comment]
This query seems fine to me.
```sql
select *
from individual i
       join program_enrolment pel on pel.individual_id = i.id
       join program_encounter pe on pe.program_enrolment_id = pel.id
       join precon_locations_view plv on plv.wadi_id = i.address_id
where not pe.is_voided
  and pe.encounter_type_id = (select encounter_type_id from operational_encounter_type where name = 'Preconception Outcome')
  and pe.observations->>concept_uuid('Last pregnancy outcome') in (concept_uuid('Live Birth'), concept_uuid('Live birth and Still birth'))
  and pe.observations->concept_uuid('Child alive till 28th day') ISNULL
  and pe.observations->concept_uuid('Mother alive till 28th day') ISNULL
  and (pe.observations->>concept_uuid('Outcome Date')) :: timestamptz
          between (select start_date from vars) and (select end_date from vars);
```
Could you share the query you used to get those numbers?
@garimadosar5

**Comment by garimadosar5** [comment]
@sidsamanvay 

I am checking this from the Pregnancy Form Extract Report. [https://app.zenhub.com/files/182039096/dfd8bec6-7646-441c-8d2a-7fc4570400fc/download](https://app.zenhub.com/files/182039096/dfd8bec6-7646-441c-8d2a-7fc4570400fc/download)
