### ISSUE TITLE
[Preconception] data changes after training.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#12]
Below are the type of changes we need to do in the system-
1. Transfer woman from one subcenter to other subcenter.
2. Transfer the woman from one village to other villages.
3. Void the duplicate women.
4. Change the scheduled date of the monthly monitoring from 09 Sep 2019 to 26 Aug 2019 and change the visit name also. [done]
5. For weight and HB, where the data is not taken, it is showing as 0. Need to fix it as NULL data. [done]

Ref doc - 
https://docs.google.com/spreadsheets/d/1mJanF-OWjcYX34zKfmMymXJA-WayVqHWv1obVq05UjQ/edit#gid=761866407

**Comment by ghost** [comment]
@garimadosar5 anything needs to be done here?

**Comment by vindeolal** [comment]
@garimadosar5 point 1,2,3 done
