### ISSUE TITLE
[Preconception Report] Analysis of Pregnancy Outcome

### ISSUE THREAD

**Issue by vinayvenu** [OpenCHS/unicef-preconception#16]
##### QA Comment - 
- ~As we are not showing the block filter we should show the block somewhere in the report because people might not know which PHC belongs to which Block.~
- Neonatal death should be (early neonatal + late neonatal) death. check for this. Currently is showing zero.
- Early/Late neonatal death calculation is not proper 1 Early neonatal is counting as 3. 
- Every case is counted in Abme PHC only. Check for the case 'test Abortion', it is registered in the Bhuvan PHC but in the report, it is showing in Ambe PHC only. **DONE**
- The indicators are sorted in alphabetical order but it should be in the order given in the spreadsheet. _NOT DONE_
- Gestational Age (9-9.99)- This is not calculating properly. There is only one case recorded. it is showing 3. - **DONE**
- Some % are not being calculated - **DONE**

- Now we have added more than 1 live birth/still birth so we have to show the info of more than one live birth in the report also.

 

##### Requirements- https://docs.google.com/spreadsheets/d/10H6eVgZG-x1vq28xIUZticmiTyMJD0Nxe9xUcCchveQ/edit#gid=1236930068
Context / Purpose of the report :
Title / Metabase Question name : Analysis of Pregnancy Outcome
Criteria / Logic for data : Logic is there in the spreadsheet
Columns (along with logic for columns except the basic ones) :Refer spreadsheet
Filters : Refer Spreadsheet

   include non enrolled individuals - N
   included exited enrolments - Y
   include cancelled encounters - NA
   included scheduled but not completed encounters - NA

Output
Metabase Question / Dashboard Link :
https://reporting.openchs.org/question/455

**Comment by garimadosar5** [comment]
QA feedback - 
~- Total stillbirths are 17. But stillbirth with congenital anamolies = 0 and without congenital anomalies = 0. The sum of both should be 17.~ - **DONE**
~- Neonatal deaths are 2 only in 'Form extract - Pregnancy Outcome'. But in this report total NNDs are 8 but Early NND is 0 and Late NND is 2. Also, early and late NNDs are not showing in the same PHC as NND PHC.~ - **DONE**
- We have added "Number of Live Births" and "Number of StillBirth" in the Oupcome form. So in case of more than one baby, we need to add that number in the report. So now calculate the number of Live and Stillbirth from this question. - **DONE**
- Also, We have added one more option "Live birth and Stillbirth" in the question "Pregnancy Outcome". In this case, we need to check for both the questions - "Number of Live birth" and "Number of still biirth". **DONE**

**Comment by garimadosar5** [comment]
QA Notes - 
@vindeolal 
- Total Outcome Reported = 685 But in Outcome form Extract = 727. (Need not to subtract Exit cases.)
- Abortion = 60 But Spontaneous + Induced Abortion = 62. - **DONE**
- Live Birth = 620 But Total Live birth weight (<2000/2000-2499/2500-3500/>3500) = 653 - **DONE**
- Total GA weeks Reported (<7/7-7.99/8-8.99/9-9.99/>9) = 639 But it should be (Total reported - Abortion). This question is mandatory for all the outcome except for Abortion cases. - **DONE**
