### ISSUE TITLE
[Preconception Reports] Form extract Report

### ISSUE THREAD

**Issue by vinayvenu** [OpenCHS/unicef-preconception#17]
##### QA Comment 2 -
- EncCancel.Nextvisitdatatime should come when the visit was cancelled, it is in Monthly visit and visit 1.
- EncCancel related columns should not be there as the Outcome will not have any cancel form.

##### QA Comment -
1. Enrolment/Baseline form extract is not there.
2. Few new questions have been added to Reg, Visit one and Monthly monitoring, please check and add them in reports also.

**Comment by garimadosar5** [comment]
QA Notes - 
- One record is coming multiple times in Registration and Enrolment.
