### ISSUE TITLE
[Preconception] Reports Bug/Changes.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#19]
#### Analysis of Monthly Monitoring - 
~- Total baseline Visits showing in the report - 2928 but total visits should be - 3574~
~- Number of Visit 1 should be - 2762~
~- The number is going up and down for Baseline 2929 (on 16 Oct) now 2928. (Check this once, the number changed between 16 Oct and 17 Oct but after that the number is same).~
- Visit expected change according to the sheet. https://docs.google.com/spreadsheets/d/10H6eVgZG-x1vq28xIUZticmiTyMJD0Nxe9xUcCchveQ/edit#gid=631452852

#### Analysis of Pregnancy Outcome - 
- Sort the PHC columns in a manner that all the PHCs in one block are together. - **DONE**
- Add two Indicators "Total Outcome Reported" (number of outcome forms filled) and  - **DONE**
- "Total Pregnant Women" (when UPT done if period missed is positive in monthly monitoring) at the starting of the report. It will help to understand the % of every indicator. 
(For total pregnant women when date filter will be applied - Total women currently pregnant in the given time period).
- Add a column with the total of that indicator for all the PHCs. for eg: Abortion Count it will show the abortion in all the PHCs (Ambe+Bhuvan+Dapur+Devpur+........) - **DONE**
- In the report, indicators are sorted in alphabetical order. sort them according to the sheet. **DONE**  
https://docs.google.com/spreadsheets/d/10H6eVgZG-x1vq28xIUZticmiTyMJD0Nxe9xUcCchveQ/edit#gid=1236930068

#### Analysis of Baseline and Visit 1
- Total baseline Visits showing in the report - 2928 but total visits should be - 3574 
(In this include Exit cases also. This report required total baseline done till now.) - _**NOT DONE**_
- The number of Visit 1 is not matching in this report and analysis of monthly monitoring report.

**Comment by ghost** [comment]
> - Total baseline Visits showing in the report - 2928 but total visits should be - 3574

- Do not compare form extract report with 'Analysis of Monthly Monitoring'.
- 'Analysis of Monthly Monitoring' is a sub set of 'Baseline/Enrolment' Form Extract report
- The numbers will vary

**Comment by vindeolal** [comment]
#### Analysis of Monthly Monitoring and Analysis of Baseline and Visit 1
- ~For baseLine count mismatch : We don't count voided enrolments, voided individuals and individuals who have exited from the program.~ - **DONE**
- Visit 1 mismatch : There was data issue with visit 13 which was wrongly mapped to visit 1 encounter type. Fixed that. - **DONE**
- Change in the number: there were some enrolments voided on oct 17 hence number changed. - **DONE**

#### Analysis of Pregnancy Outcome
Done the changes

**Comment by garimadosar5** [comment]
QA Notes - 
- Hypertension - Data is not right. for Missing - **DONE**

**Comment by garimadosar5** [comment]
QA Notes - 
Analysis of Monthly Monitoring - https://reporting.openchs.org/question/460
- Visit expected formula needs to be fixed as mentioned -  **DONE**
https://docs.google.com/spreadsheets/d/10H6eVgZG-x1vq28xIUZticmiTyMJD0Nxe9xUcCchveQ/edit#gid=631452852
- Do not remove exit cases from the report.

Analysis of Pregnancy Outcome - 
https://reporting.openchs.org/question/455?
- Total Pregnant women are coming 0 for all the PHC except DEVPUR. - **This we will move to different report as it is taking a lots of effort.**

**Comment by vindeolal** [comment]
@garimadosar5 
Analysis of monthly monitoring changes are done in line listing report
https://reporting.openchs.org/question/590

changed the pregnancy report for Pregnant women - **This we will move to different report as it is taking a lots of effort.**

**Comment by garimadosar5** [comment]
QA Notes - 
@sachsk 
1. Baseline and Baseline % rows are not there.
2. Loss to followup column is not getting calculated.
3. Visit 3 - Done, 
- We have imported 2590 visit 3
- But in the report we have 2614 visit 3.

**Comment by vindeolal** [comment]
@garimadosar5 
points 1 and 2 done.
point 3 : in db there are 2614 completed `visit 3`.
```
select count(*) from completed_program_encounter_view enc
join program_enrolment_view nepev on enc.program_enrolment_id = nepev.id
join individual_view iv on nepev.individual_id = iv.id
where enc.name = 'Visit 3'
and enc.is_voided = false
and iv.is_voided = false
and nepev.is_voided = false;
```
