### ISSUE TITLE
[Preconception] Changes/Bug after User testing.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#2]
##### Changes based on Data Import - 
- Registration form -
https://docs.google.com/spreadsheets/d/1O715jNi3WkgHw-fJPlLyFuJb_LVZKkmRrzC8dy2Y7oE/edit#gid=1871637666
   •  Add Information of Husband. - ** DONE **
- Visit 1 - 
https://docs.google.com/spreadsheets/d/1O715jNi3WkgHw-fJPlLyFuJb_LVZKkmRrzC8dy2Y7oE/edit#gid=624810993
   • Change in the options of Qus 28. IFA- Iron Folic Acid. - ** DONE**
   • Add a question after qus 29 (FA) - FA Number of Tablets given - **DONE**
   • Remove Qus 60 (Documentary) and 61 (Voice and Text msgs).  - **_NOT DONE_**
   • Add two question related to MO Examination -  after qus 58. - **DONE**

- Monthly Monitoring - 
https://docs.google.com/spreadsheets/d/1O715jNi3WkgHw-fJPlLyFuJb_LVZKkmRrzC8dy2Y7oE/edit#gid=1498369269
   • Add counselling Questions. - **_NOT DONE_**
• Outcome Form - Q6. Make it non-mandatory.
______________________________________________________________________________________________________________
                                
##### Bug -
• Visit 1 - Woman and Husband Blood group - 
    If a woman's blood group is -ve RH and husband's blood group is +ve RH then in high risk show the message "woman is Rh negative and husband is Rh positive".

##### Change - 
• Sickle cell Anemia treatment -
   This question should show up if the answer to qus 36 is Positive.  and answer of qus 37 is positive. 
• Change in Outcome form - Changes are highlighted in orange 
https://docs.google.com/spreadsheets/d/1O715jNi3WkgHw-fJPlLyFuJb_LVZKkmRrzC8dy2Y7oE/edit#gid=751524521
• Change in Monthly visit form - add LMPand EDD. (Highlighted in orange in the sheet). 
https://docs.google.com/spreadsheets/d/1O715jNi3WkgHw-fJPlLyFuJb_LVZKkmRrzC8dy2Y7oE/edit#gid=1498369269
• Change in Program Summary - Add LMP and EDD in program summary if filled in Monthly form.
https://docs.google.com/spreadsheets/d/1O715jNi3WkgHw-fJPlLyFuJb_LVZKkmRrzC8dy2Y7oE/edit#gid=1767746800
• Add a question in the Registration form - "Data Entry Operator code"
https://docs.google.com/spreadsheets/d/1O715jNi3WkgHw-fJPlLyFuJb_LVZKkmRrzC8dy2Y7oE/edit#gid=1871637666
(highlighted in the sheet).

**Comment by vindeolal** [comment]
Deployed the changes is staging.

**Comment by vindeolal** [comment]
Deployed new Changes in staging.

**Comment by nupoorkhandelwal** [comment]
In visit 1--
• Remove Qus 60 (Documentary) and 61 (Voice and Text msgs). - NOT DONE

done with this point. And have moved to staging
