### ISSUE TITLE
[Preconception][Report] Line list of women from Aggregated report.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#21]
Acceptance Criteria
- Given there is an existing aggregated report when user sees the report should be able to access line list for each indicator

Existing Aggregate Report
1. https://reporting.openchs.org/question/458.
Additional column to be added called "Line list" with columns mentioned below
2. https://reporting.openchs.org/question/460
Additional columns are to be added per column saying e.g. "Line list of BMI group less than 16"

##### Line List Columns -
- Block
- PHC
- Subcenter
- Village
- Vasti/Wadi
- Name
- Age
- Reason
- BMI/HB/Age/Blood Group/ TSH/Other Illness (TEXT)/ Calorie Intake/ Protein Intake (This column wil be based on what is the indicator. For eg: if it is HB<8 line list then it will show the HB value. If it is BMI<16 Line list, it will show the BMI value.)
- Exit Status (YES/NO)
If effort is higher than line list is must have for following indicators otherwise good to have for all indicators
#### Analysis of Monthly Report 
- BMI < 16
- BMI >30
- HB<8
- STI/RTI - YES

#### Analysis of baseline and Visit 1
- Age < 20
- Tobacco Consumption - YES
- Alcohol Consumption - YES
- Negative Blood Group - YES
- Hypertension - YES
- Diabetes - YES
- Sickle Cell - YES
- HIV - YES
- VDRL - YES
- RTI/STI - YES
- TSH-<5.00
- TSH->10.00
- Other illness - YES
- Calorie intake - <50.00% RDA
- Protein intake - <50.00% RDA

#### progress:
[588 is CLONE of 458](https://reporting.openchs.org/question/588). After QA rename the cloned one and delete the original
[590 is CLONE of 460](https://reporting.openchs.org/question/590). After QA rename the cloned one and delete the original.

**Comment by garimadosar5** [comment]
@sidsamanvay 

Where are the reports?

**Comment by ghost** [comment]
@garimadosar5 added report link

**Comment by garimadosar5** [comment]
@sidsamanvay 
QA Notes - 
- There is no link given in the aggregated report.
- All the cases with different reasons are there in the same report. Either create separate reports for every condition or provide a filter on that.

**Comment by ghost** [comment]
@garimadosar5 
could you please tell me what is this.

> There is no link given in the aggregated report.

What is this link? Where to get it? Where to put it?

> All the cases with different reasons are there in the same report. Either create separate reports for every condition or provide a filter on that.

What do they (the user of the report) want? Single or multiple? From the original details it looked like a single report.

**Comment by ghost** [comment]
dev notes.
Pending:

- followup on count mismatch.

**Comment by garimadosar5** [comment]
QA Notes - 
@sidsamanvay 
1. Age is not showing in the Age-related line list. [done]
2. And add the Age column in all the line lists. [done]
