### ISSUE TITLE
[Preconception][Support] Hide outcome form from unplanned visit if Outcome is filled once and void duplicate outcome encounter.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#26]
https://openchs.freshdesk.com/a/tickets/412

#### 2. There are a few cases where multiple outcome encounter has been done. 
               Keep the latest encounter and void rest of the duplicates.
               For eg: If two outcome encounters are done for a woman on '25-10-2019' and '28-10-2019'. We will 
               void the encounter of '25-10-2019'.

**Comment by garimadosar5** [comment]
QA Notes - 
- On staging, location is not showing and No old case is there so I cannot check.

**Comment by sachsk** [comment]
now  It is showing

**Comment by garimadosar5** [comment]
@sachsk 

Deploy it on prod.

**Comment by sachsk** [comment]
@garimadosar5 
Deployed on Prod
