### ISSUE TITLE
[Preconception] Make concepts Non-mandatory

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#3]
##### QA Comment - 
Please do the following question non-mandatory
** Registration - **
- Family Income
** Visit 1 - **
- BMI
- Preconception hypertension
- Hypertension treatment
- Any other illness
- If any other illness, specify
- Any other illness treatment

##### Registration. -Concept
Religion
Caste Category
Family Type
Cell Number
Education Level
Occupation
Total members in the family
Consanguineous marriage
Name of Husband
Age of Husband
Age of Husband at marriage

##### Baseline/Enrolment - Concept

Gravida
Parity
Date of last pregnancy outcome
Last pregnancy outcome
Live birth weight in kg
Gestational age in months for live/ Still birth/ abortion
Preconception Congenital anomaly
Tobacco consumption
Type of tobacco consumption
Alcohol consumption
Type of alcohol consumption
Meal consumption practice
Average food quantity
Food groups
Calorie intake
Calorie % RDA
Protein intake
Protein % RDA

##### Visit 1 - Concept

Preconception Weight
Hb % Level
Blood pressure systolic
Blood pressure diastolic
Blood group
Husband blood group
Sickle cell anaemia solubility test
Sickle cell anaemia electrophoresis
Blood Sugar
Preconception blood sugar ogt
HIV
HIV treatment taken
Husband hiv
HIV treatment husband
VDRL test Result
Vdrl Treatment
VDRL
Husband Vdrl Treatment
RTI Symptoms
RTI Treatment
RTI Symptoms for Husband
RTI Treatment for Husband
TSH
TSH treatment
MO Examination
Treatment taken
Deworming received- Albendazole
Iron and folic acid
Folic acid
Number of Folic Acid Tablets given
Flip book

##### Monthly Visit - Concept
Documentary film
Voice and text messages
HB %
Deworming received- Albendazole

**Comment by vindeolal** [comment]
Deployed in staging.
