### ISSUE TITLE
[Preconception][Support] Move two villages from one subcenter to other.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#30]
Ticket - 
https://openchs.freshdesk.com/a/tickets/523

Villages -
1. Pimpalpada
2. Mendpada
Currently, these two villages are showing in the "Jogmodi" Sub centre.
Move these Villages to Sub centre "Kupurli Kh".

All the cases will also move to the new Sub centre.

**Comment by sachsk** [comment]
Deployed on Staging

**Comment by sachsk** [comment]
Deployed on Production
