### ISSUE TITLE
[Precon][Support] Change the data validation in birth weight.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#32]
ticket-https://avni.freshdesk.com/a/tickets/564 

Make Birth weight validation - 800 gms-5000 gms.
After the question put the unit also. (in gms.)

Currently, some are filling in gms and some are filling in Kgs.

**Comment by vindeolal** [comment]
Deployed in staging. Once confirmed then can deploy in Prod.
