### ISSUE TITLE
[Preconception][Support] Change in weight unit for newborn babies in outcome form.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#34]
https://avni.freshdesk.com/a/tickets/611

**Comment by 1t5j0y** [comment]
SQL used for the data patch.

[https://app.zenhub.com/files/182039096/f8f9e7be-1ba3-42d0-9d04-52b1d161fa5e/download](https://app.zenhub.com/files/182039096/f8f9e7be-1ba3-42d0-9d04-52b1d161fa5e/download)
