### ISSUE TITLE
[Preconception][Support] Void extra visits for women.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#39]
https://avni.freshdesk.com/a/tickets/742

If more than one visits are done in a month then keep the last visit of that month and void all other.

**Comment by 1t5j0y** [comment]
SQL used for the data patch.

[https://app.zenhub.com/files/182039096/5fab3499-bd26-4fa1-be64-bd2c2793dc89/download](https://app.zenhub.com/files/182039096/5fab3499-bd26-4fa1-be64-bd2c2793dc89/download)

**Comment by garimadosar5** [comment]
QA Notes - 
- program enrolment id - 25799, for this case visit 20 is done twice and both the visits are non-voided.

**Comment by 1t5j0y** [comment]
Undid previous data patch which was based on year and month of encounter_date_time.
[https://app.zenhub.com/files/182039096/2e4005c7-cd3e-4083-8a83-40e5eb8c7d04/download](https://app.zenhub.com/files/182039096/2e4005c7-cd3e-4083-8a83-40e5eb8c7d04/download)

Redid the patch based on visit name.
[https://app.zenhub.com/files/182039096/abf6e317-0367-49f4-913a-ab813e2c0a15/download](https://app.zenhub.com/files/182039096/abf6e317-0367-49f4-913a-ab813e2c0a15/download)
