### ISSUE TITLE
[Precon][Support] Visit 24 is not getting scheduled

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/unicef-preconception#40]
https://avni.freshdesk.com/a/tickets/744

**Comment by 1t5j0y** [comment]
As discussed, logic used was as below:

Filter enrolments for which Visit 23 had been completed with the next visit date set to a date in July for whom Visit 24 has not been scheduled or performed.
Schedule Visit 24 for these filtered enrolments.

SQL used:
[https://app.zenhub.com/files/182039096/3c8afb9c-e077-4717-ab64-a79639ee3844/download](https://app.zenhub.com/files/182039096/3c8afb9c-e077-4717-ab64-a79639ee3844/download)
